ZakStrassberg/YPC-scrum

bower.json, client/app.js, client/controllers/indexController.js, client/factories/dummyFactory.js, client/index.html, client/partials/index.html, package.json, server.js, server/config/routes.js, server/models/model.js
This is the initial version of the project with a working server.js and some dependencies brought in. 
Check package.json to see current deps.
=> YPC scrum project skeleton

README.md
I added a description of YPC and added links to our githubs, linkedins, and websites. Let me know if you would like additional information added. 
I was also thinking about adding pictures of us. :)
=> Readme updated with developer links and description

package.json
Comma missing, causing "npm install" to fail.
Also adding aws-sdk for S3 file uploading.
=> fixed dependencies for npm install to work. Introduced aws-sdk

README.md, client/partials/join.html, client/partials/signup.html
Simple HTML skeletons based on the YPC Membership Form PDF.
They will need to match the DB eventually. We will also need to add payment forms in sprint 2.
Added Carmen's GitHub url.
=> Created HTML forms for Sign Up and Joining a Committee. Added Carmen's GH Link

client/register.html, server.js, server/config/doquery_function.js, server/config/mysql.js, server/config/routes.js, server/controllers/controller_template.js, server/controllers/registrationController.js, server/models/model_template.js
doQuery now returns an object {rows, err, fields}
so you can call the model function, get the result, and respond from the controller
=> some changes to model and controller templates, doQuery function

client/partials/admin.html, client/partials/join.html, client/partials/posts/create.html, client/partials/posts/delete.html, client/partials/posts/edit.html, client/partials/posts/show.html, client/partials/signup.html
we will use ejs for the admin panel.
we need to create RESTful routes for posts.
=> updated html forms and added posts 

client/register.html, server/config/doquery_function.js, server/controllers/controller_template.js, server/controllers/registrationController.js, server/models/model_template.js, server/models/registrationModel.js
this changes how models and controllers work if you do any queries
=> doQuery now uses a callback, updated templates to match

client/blog.html, client/contact.html, client/events.html, client/executives.html, client/index.html, client/sign_in.html
=> Added Sign in page

server/config/routes.js, server/controllers/userController.js, server/views/users/edit.ejs
These are not hooked up to the db yet. This has all the info that YPC wants to store.
=> Added userController, added user info page

client/login.html, server/config/mysql.js, server/config/routes.js, server/controllers/loginController.js, server/controllers/registrationController.js, server/models/loginModel.js, server/views/sign_in.ejs
Connected backend to frontend for login
=> modified login files

server/config/routes.js, server/controllers/uploadController.js, server/views/admin/upload/index.ejs
Adding view and delete file capability to upload controller.
Not done with AJAX. Pending conversion to AJAX version (or at least auto page refresh after CRUD).
=> View/Download file & delete file on S3

client/js/upload.js, server/controllers/uploadController.js, server/views/admin/upload/index.ejs
1. Page does not reload after uploading a file, and displays new file & details on page.
2. Page does not reload after deleting a file, and removes the deleted file & details from page.
=> Converted to AJAX for uploading and deleting files

README.md, server/config/generateNavBar_function.js, server/config/routes.js, server/controllers/loginController.js, server/controllers/pageController.js, server/controllers/registrationController.js, server/models/loginModel.js, server/models/registrationModel.js
=> session DONE

server/controllers/userController.js, server/models/userModel.js, server/views/users/edit.ejs
added functionalities that allow user to update their profile
=> edit user functionalities

YPCdb.sql
=> adding sql script

server/config/generateNavBar_function.js, server/config/mysql.js
the default mysql port is 3306 and we had too much trouble changing it on the deployed instance, so it will be easier if we use 3306.
=> brought back navbar button and changed mysql port to 3306

client/js/upload.js, server/views/admin/upload/index.ejs
In upload page, when newly uploaded files are added, "view file" button is shown instead of "view" button. Changed to "view" button for consistency.
=> change view file button to view for consistency

client/css/style.css
fixed the nav bar so users won't have to scroll down to see it, fixed the  padding since it doesn't need to be 25px, also added a hover and active colour"
=>  #13- Not require scroll down to see the nav bar and YPC logo

server/config/generateNavBar_function.js, server/config/routes.js, server/views/blog.ejs, server/views/contact.ejs, server/views/donate.ejs, server/views/executives.ejs, server/views/join.ejs, server/views/sign_in.ejs
Need clarification from Jay or Paul tomorrow about YPC's SSL Certificate before proceeding.
=> added donate page, now on the navBar as well

server/config/generateNavBar_function.js
Fixed Sign in button to Nav bar
=> Fixed Sign in button to Nav bar

server/views/donate.ejs
=> added VMC Foundation link

client/css/style.css, server/views/index.ejs
added social media icons ontop of navbar, and linked them
=> added social media icons ontop of navbar, and linked them

client/README.txt, client/css/style.css, server/config/generateNavBar_function.js, server/views/blog.ejs, server/views/contact.ejs, server/views/donate.ejs, server/views/events.ejs, server/views/executives.ejs, server/views/index.ejs, server/views/join.ejs, server/views/sign_in.ejs
Cleaned up navBar and edited various pages
=> Cleaned up navBar and edited various pages

server/views/blog.ejs, server/views/contact.ejs, server/views/donate.ejs, server/views/events.ejs, server/views/executives.ejs, server/views/index.ejs, server/views/join.ejs, server/views/sign_in.ejs
Added committee selection option
=> Added committee selection option

client/css/style.css, server/views/executives.ejs
Reduced Join padding from overlapping with Twitter Link
=> Reduced Join padding from overlapping with Twitter Link

server/config/routes.js, server/views/executives.ejs, server/views/join.ejs
Fixed the following errors:
1. Removed erb code and put in strictly ejs code
2. Removed syntax errors (extra >s)
3. Added <%= tags as needed
4. Removed hardcoded content from executives page
=> fixed executive page ejs
